### ISSUE TITLE
Stworzyć powtarzalny schemat manualnych testów

### ISSUE THREAD

**Issue by maciekkukuczka** [maciekkukuczka/Docs#171]
Chodzi o powtarzalność testów, by za każdym razem testować zasadnicze elementy czy nic się nie popsuło.
Czyli np.:

Test 1 - BEZPIECZEŃSTWO
1. Stworzyć Użytkownika
2. Stworzyć 2 tematy
3. Sprawdzić czy tematy nie przeciekają miedzy użytkownikami.
4. …

Test 2 - KATEGORIE
1. Stworzyć 2 kategorie.
2. Kliknąć w każdą i sprawdzić czy dokumenty się filtrują
3. ...

TAKI TEMAT ZAŁÓŻ PROSZĘ NA GITHUBIE W ZAKŁADCE WIKI I TAM GO SOBIE UZUPEŁNIAJ.
Ja mam taki schemat stworzony tam dla Deployowania, wiec możesz sobie podpatrzyć.
Później otwierasz taki dokument i postępujesz według zapisanej procedury. 
Zapewni nam to powtarzalność testów.

**Comment by Agnieszka101** [comment]
Oookej, chyba wiem o co chodzi, muszę sobie to tylko poukładać🙂
