### ISSUE TITLE
Users subjects can only show in user context - security problem!

### ISSUE THREAD

**Issue by maciekkukuczka** [maciekkukuczka/Docs#172]
- docs should contain safeguard against seen doc by another user
- what with paste doc address (id) to browser directly?

**Comment by maciekkukuczka** [comment]
wklejając bezpośredniego linka do dokument w przegladarke, system nie sprawdzał czy ktoś ma prawa dostepu, wiec przepuszczał wszystkich z ulicy. Teraz sprawdza czy dokument w swoich tematach posiada jakiegokolwiek użytkownika o zgodnym id. (Niestety odbywa się to olbrzymim kosztem wydajności przy takim zapytaniu, wiec w przysłości trzeba to zmienić).

Żeby przetestować należy:
- zalogować się na jakiegoś użytkownika 
- wejśc w jakiś jego dokument
- skopiować linka z id dokumentu
- wylogować się
- zalogować jako inny użytkownik
- wkleic skopiowanego linka z dokumentem od innego użytkownika

Powtórzyć test na zupełnie wylogowanym użytkowniku

**Comment by Agnieszka101** [comment]
- zarejestrowanie nowego użytkownika
- zalogowanie się na jego konto
- utworzenie tematu
- utworzenie dokumentu
Po próbie wejścia w Dokument jako użytkownik konta, wyświetla się następujący komunikat 


![Image](https://github.com/user-attachments/assets/407b42a3-ad0b-49b9-a5b4-d868d76d6a1e)
