### ISSUE TITLE
Tagi

### ISSUE THREAD

**Issue by Agnieszka101** [maciekkukuczka/Docs#175]
Niepoprawne działanie Tagów, po oznaczeniu trzeciego taga, zaznacza się czwarty, a odznaczony czwarty po najechaniu w ogóle nie reaguje, tym samym trzeci i czwarty Tag nie działają poprawnie.

**Comment by maciekkukuczka** [comment]
Pierwsza iteracja naprawy tagów.
- zmieniono system wyszukiwania i dystrybucji tagów miedzy komponentami.
- dodano tagi do wyszukiwarki.
