### ISSUE TITLE
Add images crud page

### ISSUE THREAD

**Issue by maciekkukuczka** [maciekkukuczka/Docs#191]
Dodano stronę "Zdjęcia". Trzeba ogólnie sprawdzić jak działaja wszystkie operacje CRUD czyli tworzenie, edytowanie, kasowanie.
NO i wszystko co przyjdzie pani do głowy związane z tą podstroną.
Sam wyglad elementów jak zwykle zostawiam pani wiec proszę sobie odpowiedniego taska ku temu stworzyć samodzielnie 😎.
Przypominam , ze testowanie to nie tylko wykrywanie błędów, ale i pani uwagi co do funcjonalności (bo z wygladem poradzi sobie pani sama 😜), propozycje , pomysły itd. Te ewentualnie proszę zamieszczać w taskach już stworzonych jeśli są ku temu odpowiednie, albo w nowych.

**Comment by Agnieszka101** [comment]
Samo dodanie strony ze Zdjęciami powiodło się, dlatego sądzę, że tego taska można uznać za skończonego, ponieważ wszelkie dalsze prace nad tą stroną będą prowadzone indywidualnie, w odniesieniu do każdego pojawiającego się problemu, lub w zamiarze udoskonalenia samej strony jako takiej.
