### ISSUE TITLE
Nie działają fajkowe dane.

### ISSUE THREAD

**Issue by Agnieszka101** [maciekkukuczka/Docs#205]

**Comment by maciekkukuczka** [comment]
- Poprawiono generowanie danych dla nowych włąściwości (subjectId)
- Zmioeniono metode przekazywania zdjęcia do galerii (z bazy danych na parametr)
- Dodano zdjęcia

UWAGA!! NALEŻY DOBRZE SPRAWDZIĆ CZY NIE POWÓCIŁ PROBLEM WYCIEKU ZDJEĆ LUB INNY PROBLEM ZWIAZANY ZE ZDJĘCIAMI

**Comment by Agnieszka101** [comment]
Jedyny problem jaki się pojawia, chociaż nie do końca wiem czy to problem, czy prawidłowa reakcja, to gdy na plusiku doda się zdjęcie i chce się je usunąć , zanim zapisze się na stronie, to wyświetla się taki komunikat. Ale to chyba dlatego, że zanim zapisało się na stronie, chce się je usunąć i system nie zdążył rozpoznać.


![Image](https://github.com/user-attachments/assets/28d9dd3d-4968-4444-8b68-0892ca2ad60f)

**Comment by maciekkukuczka** [comment]
no tak, usiłuje skasować plik, którego nie ma...ale to jest do poprawy generalnie. Zobacz czy teraz dalej się pojawia.

**Comment by Agnieszka101** [comment]
Tak, dalej

**Comment by maciekkukuczka** [comment]
Znaczy po updejcie? Ja tego nie potrafie powtórzyć, jaka jest dokładna procedura? Zdjęcia czy doc?

**Comment by Agnieszka101** [comment]
tak, po up dalej wyświetla się na czerwono. A procedura taka, jak wyżej jest opisane. Dodajesz zdjęcie na plusiku, ale zanim zapiszesz na stronie, usuwasz je.


![Image](https://github.com/user-attachments/assets/a3139412-cb6e-408d-bafd-0a65fec74116)

Tylko Ty poprawiłeś tak, że ten komunikat nie ma się wyświetlać?

**Comment by Agnieszka101** [comment]
a sorry, miałam dopowiedzieć, że na stronie edytowanej, czyli na doc

**Comment by maciekkukuczka** [comment]
> tak, po up dalej wyświetla się na czerwono. A procedura taka, jak wyżej jest opisane. Dodajesz zdjęcie na plusiku, ale zanim zapiszesz na stronie, usuwasz je.
> 
> ![Image](https://github.com/user-attachments/assets/a3139412-cb6e-408d-bafd-0a65fec74116)
> 
> Tylko Ty poprawiłeś tak, że ten komunikat nie ma się wyświetlać?

skor sie wuświetla to nie poprawiłem 😜 Już mam dość tych zdjęcć, po trenigu dorobie edycje na doc, tyllko na pisz prosze taska...
