### ISSUE TITLE
Sprawdzić rozdzielczość zdjęć.

### ISSUE THREAD

**Issue by Agnieszka101** [maciekkukuczka/Docs#207]

**Comment by maciekkukuczka** [comment]
Tu sytuacja jest jasna i wynika skąd pochodzą wyswietlane sa zdjęcia.
Jesli z preview to rozdzeilczosć jest ustawiona na symboliczną , jesli już z plikyu , to taka jak ma prawdziwe zdjkęcie.
Previev wyswietlane sa w momencie dodawania zdjęcia, gdy nie ma ich jescze zapisanych na dysk.

Jesli była by potrzeba zapisywania od razu po wczyztaniu zdjęcia to trzeba przerobic mechanizm wczytywania.



![Image](https://github.com/user-attachments/assets/356e4fb5-51cd-43d9-8e90-b594c7140eb8)

**Comment by Agnieszka101** [comment]
Świetnie, wiemy co jest powodem takiego wyświetlania zdjęć, tylko co ja mam z tym zrobić? Zostawiamy takie wczytywanie i przepuszczamy taska, czy przerabiasz mechanizm wczytywania...

**Comment by maciekkukuczka** [comment]
ja bym na razie zostawił i obserwował. Jak zajdzie potrzeba, to sie po prostu napisze taką funkcjonnalność, ale nie wiem czy to konieczne...🤔

**Comment by Agnieszka101** [comment]
![Image](https://github.com/user-attachments/assets/4904e961-3676-44b1-9af8-8e5314eae036)

moim zdaniem, to średnio wygląda na obecną chwilę, ale ok, zostawiamy w takim razie

**Comment by maciekkukuczka** [comment]
ale one sa tylko w preview wyswietlane w momncie dodawania, przed plusikiem. Poiznasz po tym, że na narzedziach bedzie dłuuuugoi link. w innych momentach sa juz czytane z dysku. 
No a co do ich wygladu to wiadomo kto co 😜😜

**Comment by Agnieszka101** [comment]
takie poucinane są wyświetlane na stronie nie edytowanej, czyli tak naprawdę na głównej stronie, są tam umieszczone na sztywno i tak się zastanawiam czy właśnie na tej stronie nie warto by dodać to powiększenie, bo oprócz poprawnego wyglądu, fajnie by bylo gdyby się w calości wyświetlały. Na obecną chwilę taką możliwość daje tylko strona edytowana.

**Comment by maciekkukuczka** [comment]
oczywiście, można To kwestia wyłacznie frontendu

**Comment by maciekkukuczka** [comment]
Teraz. obrazki w większych oknach czytane sa zawsze z dysku jeśli jest to możliwe.
