### ISSUE TITLE
Samo kasowanie się zdjęć

### ISSUE THREAD

**Issue by Agnieszka101** [maciekkukuczka/Docs#222]
Przy próbie dodania drugiego zdjęcia na stronie edytowanej, automatycznie kasują się wszystkie zdjęcia.

**Comment by maciekkukuczka** [comment]
Rozwiązanie tymczasowe , polegające na zablokowaniu wczytywania wielu zdjęć na raz bez zatwierdzenia ich (plusikiem).
Dalsze prace będą podejmowane, gdy zajdzie potrzeba wczytywania wielu zdjęć naraz, bo wiązę się to z wieloma pracami.

**Comment by Agnieszka101** [comment]
To nie chodzi o wczytywanie, bo kasowanie następuje przy próbie dodania na plusiku kolejnego zdjęcia. Ale rozumiem, że trzeba będzie po każdym dodaniu zdjęcia, najpierw zapisać całą stronę, by móc dodać kolejne zdjęcie.

**Comment by maciekkukuczka** [comment]
Do sprawdzenia
