### ISSUE TITLE
Przeciek tagów na produkcji między userami, przeciek dotyczy strony edytowanej

### ISSUE THREAD

**Issue by Agnieszka101** [maciekkukuczka/Docs#225]
Proszę sprawdzic jeszcze, bo ja nie umiem powtórzyć tego błedu, u mnie działą ¯\_(ツ)_/¯

**Comment by Agnieszka101** [comment]
![Image](https://github.com/user-attachments/assets/f0e7ca01-e767-4ed6-b025-aa4b0e4df14c)

**Comment by maciekkukuczka** [comment]
ale to jest na Produkcji, ana dev już jest poprawka do tego.

**Comment by Agnieszka101** [comment]
cały czas przeciek dotyczył Produkcji, a na Dev na stronie edytowanej, Tagi w ogóle zniknęły

**Comment by maciekkukuczka** [comment]
Ja wiem, ze tdotyczył produkcji, ale poprawkę do tego dodałem do gałezi dev, zanim zrobi się deploy na produkcję...
No i u mnie sa te tagi

**Comment by Agnieszka101** [comment]
no to u Ciebie są a u mnie ich nie ma

**Comment by Agnieszka101** [comment]
![Image](https://github.com/user-attachments/assets/05404c4a-5f63-49f1-bc97-876a4d5b19f0)

nie wiem czy ten nawias ich nie blokuje

**Comment by maciekkukuczka** [comment]
a możesz baze usunać i sprawdzić, bo oan już długo jest u pani i sporo zmian zaszło. Oczywiście wszystko pani straci, wiec przypominam o kompiowaniu.

ps. po jednokrotnym uruchomieniu apki ,przestawić z powrotem ensuredeleted na false, bo bedzie kaslował za każdym uruchomieniem. 



![Image](https://github.com/user-attachments/assets/33c5bd2e-7455-4e4f-a051-63349e3f3066)

**Comment by maciekkukuczka** [comment]
> ![Image](https://github.com/user-attachments/assets/05404c4a-5f63-49f1-bc97-876a4d5b19f0)
> 
> nie wiem czy ten nawias ich nie blokuje

update zrób też

**Comment by Agnieszka101** [comment]
tagi działają, baza przestawiona, update zrobiony, nawias jak był, tak jest
