### ISSUE TITLE
Edit page is null if refresh

### ISSUE THREAD

**Issue by maciekkukuczka** [maciekkukuczka/Docs#242]
Gdy wchodziliśmy na dokument a potem go odświeżyliśmy , to otrzymywaliśmy pustą stronę. Teraz powinno być ok.
Kojarze też , że inne sytuacje wywoływały pustość strony, ale nie moge sobie przypomniec jakie, wiec potestuj proszę.

**Comment by Agnieszka101** [comment]
to chyba było też przy przelogowaniu, ale nie jestem pewna, sprawdzę
