### ISSUE TITLE
If we back in history (back arrow) and we iterate after docs pages then previous page has good url but content remains same as current page

### ISSUE THREAD

**Issue by maciekkukuczka** [maciekkukuczka/Docs#243]
Podczas przemieszcanie się miedzy dokumentami, gdy postanawialiśmy się cofnąć za pomocą strzałki w tył zarówno w przeglądarce jak i nowej Szczauuki (czyli gdy użwywaliśmy historii przeglądani) , to poszczególne dokumenty zmieniały prawidłowo adres, jednak treść pozostawała ze "starego" dokumentu -   nie ładował sie nowy dokument.

Teraz powinien ładować tresć dokumentu, na który wskazuje url prawidłowo, jednak należy zwrócić uwagę czy nie przyniosło to negatywnych konsekwencji w innych miejsca, w szcególności podczas przemieszczania się miedzy stronami.

**Comment by Agnieszka101** [comment]
dobrze...
