### ISSUE TITLE
błąd przy odświeżaniu edycji, nie wczytują się wszystkie zdjęcia na stronie edytowanej

### ISSUE THREAD

**Issue by Agnieszka101** [maciekkukuczka/Docs#244]
dokument na stronie nie edytowanej=>strona edytowana=>odświeżenie=strona nie edytowana=>edycja i tu następuje błąd

**Comment by maciekkukuczka** [comment]
Nie potrafie powtórzyc tego błędu u siebie. Musimy zdebugowac to u Pani. (sprwadzić relacje w bazie)
