### ISSUE TITLE
MiniCrudComp unification to use MacSubmit and rename to MacMiniCrud

### ISSUE THREAD

**Issue by maciekkukuczka** [maciekkukuczka/Docs#248]
- Zunifikowano do standardu uzywajacego jak formularza edycji MacSubmit. (Generycznosć komponentu)
- Zunifikowano nazwe do standadardu MacNazwaKomponentu

Ten komponent użyty jejst do wprowadzania linków, wiec trzeba sprawdzić czy wszystko działa jak poprzednio.

**Comment by Agnieszka101** [comment]
Chodzi o to czy w ogóle linki działają poprawnie?

**Comment by maciekkukuczka** [comment]
Raczej edycja i wprowadzanie linków , bo "pod maską" jest teraz generyczny MacSubmit (czyli ten który poprawialiśmy wczoraj), zamiast poprzedniego.

**Comment by Agnieszka101** [comment]
Ok🙂
