### ISSUE TITLE
Save button active, only when Doc changed

### ISSUE THREAD

**Issue by maciekkukuczka** [maciekkukuczka/Docs#251]
Przycisk "Zapisz" powinien być aktywny tylko wtedy, gdy jakieś wartości w polach zostały zmieniony.

**Comment by maciekkukuczka** [comment]
Przycisk "Zapisz" powinien być aktywny tylko wtedy, gdy jakieś wartości w polach zostały zmienion"

**Comment by Agnieszka101** [comment]
czy te wartości w polach dotyczą tylko tekstu, czy też brane są pod uwagę zmiany np w kategoriach i tagach, pytam ponieważ wprowadzone zmiany we wspomnianych nie aktywują przycisku Zapisz
