### ISSUE TITLE
Show title in Section bar if we scroll down page 

### ISSUE THREAD

**Issue by maciekkukuczka** [maciekkukuczka/Docs#252]
Mechanizm pokazywania tytułu w górnej sekcji, gdy zjeżdzamy w dół i oryginalny tytuł dokumentu znika nam z pola widzenia.

**Comment by Agnieszka101** [comment]
Tytuł jest na sztywno "przyklejony" tak?

**Comment by Agnieszka101** [comment]
Mam na myśli, że jak zjeżdżam na dół, to tytuł pozostaje niewzruszony na górze, czyli takie scrollowanie strony, ale to chyba nie jest tak jak sobie wyobrażam🙂

**Comment by maciekkukuczka** [comment]
https://github.com/user-attachments/assets/e0495775-9f5c-4ca2-9aeb-046fb8ef6beb

**Comment by Agnieszka101** [comment]
a już wiem o co chodzi

**Comment by Agnieszka101** [comment]
swoją drogą autko bardzo ładne, choć nie tanie, ale ta baba, którą ciągle wciskasz, to brzydka, chociaż to może kwestia gustu ;)

**Comment by maciekkukuczka** [comment]
łooo pani , takie mam zdjecia w katalogu, który mi się podpowiada przy wczytywaniu zdjec 😜
A Pani Torkowska to jedyna polityk, jaką toleruje 😜 i proszę się nie zajmować gupotami , bo szkoda czasu...

**Comment by Agnieszka101** [comment]
pan to sobie może mieć co tam pan chce w tych katalogach, ale prosiłabym aby wspólną przestrzeń roboczą z czystej przyzwoitości trzymał pan z daleka od pańskiej "babskiej pornografii"...
