### ISSUE TITLE
Add Cancel operation button to Cruds.

### ISSUE THREAD

**Issue by maciekkukuczka** [maciekkukuczka/Docs#65]
Dodano przycisk anulowania edycji danej encji.
- po kliknieciu w ołóweczek powinien pojawić się dodatkowy przycisk anulowania operacji i wyczysczenia wszystkich pół formularza.

- po anulowaniu , przyciski innych encji z listy powinny wrócić do  statusu aktywnenego, czyli powinny dac się kliknać.

Sprawdzić również czy operacja anulowania nie wprowadza jakiś powikłań przy zapisywaniu i edycji.

**Comment by Agnieszka101** [comment]
1. Po wciśnięciu ołówka w Kategoriach, wyświetla się jakaś nazwa Kategorii do edycji. 
Następnie iksem anuluje się operację, wszystkie ikonki wracają prawidłowo. 
Ale chcąc edytować jeszcze raz tą samą nazwę Kategorii, już się ona nie wyświetla.

2. nastepuje nadpisanie modelu juz momencie edycji, a nie w momencie submitu.
