### ISSUE TITLE
Add Back arrow button

### ISSUE THREAD

**Issue by maciekkukuczka** [maciekkukuczka/Docs#66]
Strzałka ma  celu wracanie na poprzednią stronę, według historii.
Na tą chwile sięga jedynie krok do tyłu do pamięci, jednak można rozbudować by wracał po kolei tak jak użytkownik chodził po stronie.

**Comment by Agnieszka101** [comment]
strzałka cofa o każdy kolejny jeden krok do tyłu według historii, ale gdyby się za daleko poszło o jedną stronę, to rozumiem, że można ustawić tak by nie tylko cofała, ale o ten jeden krok do przodu wracała tak?

**Comment by maciekkukuczka** [comment]
to szczauka tylno boczna, wiec nie ma mozliwości chodzenia do przodu 😉
